version: "3.9"
services:
  api:
    build: ../
    env_file: ../.env
    ports: ["8080:8080"]
    volumes:
      - ../:/app
  weaviate:
    image: semitechnologies/weaviate:1.25.7
    restart: unless-stopped
    ports: ["8081:8080"]
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-transformers"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data: